Prevent merges from breaking codegen
enabled automerge a little too quickly..

Signed-off-by: clux <sszynrae@gmail.com>

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -40,3 +40,32 @@ jobs:
       - name: Run workspace doc tests
         run: cargo test --workspace --doc
         if: false # currently go doc generates stuff that rust expects to be valid symbols
+
+  codegen:
+    strategy:
+      # Prevent GitHub from cancelling all in-progress jobs when a matrix job fails.
+      fail-fast: false
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+      - uses: actions-rs/toolchain@v1
+        with:
+          override: true
+          toolchain: stable
+          profile: minimal
+      # Smart caching for Rust projects.
+      # Includes workaround for macos cache corruption.
+      # - https://github.com/rust-lang/cargo/issues/8603
+      # - https://github.com/actions/cache/issues/403
+      - uses: Swatinem/rust-cache@v2
+
+      - run: just protos
+      - run: just swagger
+      - run: just codegen
+      - name: Ensure generated output is committed
+        run: |
+          if ! git diff --exit-code .; then
+              echo "Uncommitted changes"
+              echo "Please run codegeneration locally and commit the results"
+              exit 1
+          fi
